// this is for microservices config server centralized or externalized configuration
insurance.provider.url = http://localhost:8080/insurance/all-plans

spring.application.name=user-service-config-via-config-server
eureka.client.registerWithEureka=true
eureka.client.fetchRegistry=true
